### ISSUE TITLE
Additional Resources to Consider

### ISSUE THREAD

**Issue by NyamiDev** [MrM8BRH/Privacy-Security-FOSS-Resources#1]
For servers you host at home may I suggest Start9 labs and their product StartOS.

https://start9.com/

I think using a product like this to host data, photos, password managers etc, all from your own home that you can share with friends and family is a very good thing. 

A distant second to the above is Umbrel, but I would definitely go with start9 for added security. 
[umbrel.com](https://umbrel.com/)

Chat app:
https://simplex.chat/

A good resources website:
https://privacytools.guide

Great resource, best of luck. 

ND

**Comment by MrM8BRH** [comment]
Thank you for sharing resources! I've added it to my GitHub repo, and the others I've added to my start.me bookmarks (https://start.me/p/KMqznE/it-cyber-security). 
![image](https://github.com/MrM8BRH/Privacy-Security-FOSS-Resources/assets/34133187/84d86352-d0de-4871-a7fe-9485af4765ca)


Best Regards <3
